version: '3'

services:
  env_quantlib:
    image: env_quantlib:${QL_TAG}
    build:
      context: ../
      dockerfile: Docker/Dockerfile-QuantLib
      args:
        - boost_version=1.72.0
        - num_cores=16
