version: '3'

services:
  env_quantlib:
    image: env_quantlib:1.18_7466c7286
    build:
      context: ../
      dockerfile: Docker/Dockerfile-QuantLib
      args:
        - boost_version=1.72.0
        - num_cores=16
