version: '3'

services:
  ore_app:
    image: ore_app:${ORE_TAG}
    cap_drop:
      - NET_RAW
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE-App
      args:
        - ORE_VERSION=${ORE_TAG}
        - ORE_HELPER_VERSION=${ORE_HELPER_VERSION}
