version: '3'

services:
  ore-build-dependencies:
    image: ore-build-dependencies:latest
    cap_drop:
      - NET_RAW
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE-Dependencies
      args:
        - debian_tag=${DEBIAN_TAG}
