version: '3'

services:
  env_quantlib_debug:
    image: env_quantlib_debug:1.18_071a68fbbc
    build:
      context: ../
      dockerfile: Docker/Dockerfile-QuantLib-Debug
      args:
        - boost_version=1.72.0
        - num_cores=16
