version: '3'

services:
  build_env_boost:
    image: ore-helper:latest
    cap_drop:
      - NET_RAW
    build:
      context: .
      dockerfile: Dockerfile-Test
      args:
        - DEBIAN_TAG=${DEBIAN_TAG}
