version: '3'

services:
  build_env_boost_debug:
    image: build_env_boost_debug:${BOOST_TAG}
    build:
      context: .
      dockerfile: Dockerfile-Boost-Debug
      args:
        - boost_version=${BOOST_TAG}
        - boost_dir=boost_${BOOST_DIR}
        - boost_variant=debug
        - num_cores=16
        - debian_tag=${DEBIAN_TAG}
