version: '3'

services:
  ore_plus_app:
    image: oreswig_app:${ORE_TAG}
    build:
      context: ../../../
      dockerfile: ore/ORE-SWIG/Docker/Dockerfile-ORESWIG-App
      args:
        - ORE_VERSION=${ORE_TAG}
        - ORE_HELPER_VERSION=${ORE_HELPER_VERSION}
        - DEBIAN_TAG=${DEBIAN_TAG}
