version: '3'

services:
  ore_plus_app:
    image: oreswig_app:${ORE_TAG}
    build:
      context: ../../../
      dockerfile: oreswig/Docker/Dockerfile-ORESWIG-App
      args:
        - ore_version=${ORE_TAG}
        - debian_tag=${DEBIAN_TAG}
