version: '3'

services:
  env_ore_plus_swig:
    image: env_oreswig:${ORE_TAG}
    build:
      context: ../../../
      dockerfile: ore/ORE-SWIG/Docker/Dockerfile-ORESWIG
      args:
        - ORE_VERSION=${ORE_TAG}