version: '3'

services:
  simplefileserver:
    image: simplefileserver:latest
    ports:
      - "8080:5000"
    volumes:
      - C/Dev/oreplus/ore/Api/app/Input
      - C/Dev/oreplus/ore/Api/app/Output

