version: '3'

services:
  restapi:
    image: restapi:latest
    networks:
      - postman
    ports:
      - "5001:5001"

  simplefileserver:
    image: simplefileserver:latest
    env_file:
      - docker-envfile.env
    environment:
      - INPUT_DIR=${INPUT_DIR:-./Examples/Input}
      - OUTPUT_DIR=${OUTPUT_DIR:-./Examples/Output}
    volumes:
      - "${INPUT_DIR:-./Examples/Input}:/app/Input"
      - "${OUTPUT_DIR:-./Examples/Output}:/app/Output"
    networks:
      - postman
    ports:
      - "5000:5000"

networks:
  postman:
