name: Linux x86_64 ManyLinux Wheels (pp*)

on:
  workflow_dispatch:

jobs:
  wheels-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ORE
      uses: actions/checkout@v4
      with:
        submodules: recursive
    #- name: get QuantLib Submodules
    #  run: |
    #    git submodule update --init --recursive
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - name: Install eigen
      run: |
        curl -O -L https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
        tar zxvf eigen-3.4.0.tar.gz
        cd eigen-3.4.0
        mkdir build
        cd build
        cmake ..
        export 
        export Eigen3_DIR=$CURRENT_DIR/eigen-3.4.0
    - name: Build Zlib
      run: |
        pwd
        curl -O -L https://www.zlib.net/zlib-1.3.1.tar.gz
        tar xzvf zlib-1.3.1.tar.gz
        cd zlib-1.3.1
        ./configure
        make
        export ZLIB_ROOT=$CURRENT_DIR/zlib-1.3.1
    - name: Copy Configuration
      run: |
         pwd
         cp ORE-SWIG/Wheels/oreanalytics-config.linux ORE-SWIG/oreanalytics-config
         chmod +x ORE-SWIG/oreanalytics-config
         cd ORE-SWIG/Wheels
         chmod +x before_all_linux.sh
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_BUILD: "*-manylinux_x86_64"
        CIBW_SKIP: cp*
        #CIBW_BUILD: cp37-manylinux_x86_64
        #CIBW_BUILD: cp38-manylinux_x86_64
        #CIBW_BUILD: cp39-manylinux_x86_64
        #CIBW_BUILD: cp310-manylinux_x86_64
        #CIBW_BUILD: cp311-manylinux_x86_64
        CIBW_ARCHS_LINUX: x86_64
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./ORE-SWIG/Wheels/before_all_linux.sh
        #CIBW_ENVIRONMENT_LINUX: CXXFLAGS="-O3 -g0"
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS="-std=c++17 -O3 -g0" ORE=/project
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS
      with:
        package-dir: ${{ github.workspace }}/ORE-SWIG
    - name: Save wheels as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: wheels-linux-manylinux-x86_64
        path: ./wheelhouse/*.whl
